### ISSUE TITLE
Add new PyCubed images to website

### ISSUE THREAD

**Issue by zacmanchester** [RoboticExplorationLab/roboticexplorationlab.github.io#3]
Also add links to the documentation and SmallSat paper to the project page

**Comment by maholli** [comment]
Added 

1. [ed9ff93](https://github.com/RoboticExplorationLab/roboticexplorationlab.github.io/commit/ed9ff93e3a9706e6752400f06e7b8361ed3fe8d2)
2. [7807d8e](https://github.com/RoboticExplorationLab/roboticexplorationlab.github.io/commit/7807d8ef42dc9d76475fa9d4918278efd19df593)
